### ISSUE TITLE
Twitch badges (mods, subs, etc.)

### ISSUE THREAD

**Issue by hellishvictor** [Chatterino/chatterino2#4071]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hi, the badges of the channels from twitch doesn't appear at all (streamer, mods, subs, etc). On "Visible badges" I have all of them checked.
Cheers.

### Screenshots

![sshot-1](https://user-images.githubusercontent.com/34694956/196841612-d686e587-8422-40f8-b641-592847e4c710.jpg)

### OS and Chatterino Version

Chatterino 2.3.5 (commit 81a62764c) Win7x64

**Comment by Felanbird** [comment]
All of those badges are Twitch badges and we get those badges directly from Twitch, I'm almost 99.9999% sure it's an issue between your ISP and Twitch.

**Comment by hellishvictor** [comment]
> All of those badges are Twitch badges and we get those badges directly from Twitch, I'm almost 99.9999% sure it's an issue between your ISP and Twitch.

Don't think so, I can see them on my OBS and Firefox.

**Comment by hellishvictor** [comment]
> Can you share a screenshot of what this page looks like on your computer https://t.3v.fi/badges.html

![sshot-1](https://user-images.githubusercontent.com/34694956/196854908-bf668667-ac22-40fc-a2c0-c9a7ae942e73.jpg)

**Comment by Felanbird** [comment]
> Don't think so, I can see them on my OBS and Firefox.

Twitch loads their badges from a different place than Chatterino can, but it is the same place as the link iProdigy posted.

**Comment by iProdigy** [comment]
Can you try to clear the cache (Settings -> General -> AppData & Cache)?

**Comment by hellishvictor** [comment]
> Can you try to clear the cache (Settings -> General -> AppData & Cache)?

Yeah, but is still the same. I'm using the portable version btw.

**Comment by hellishvictor** [comment]
I've downloaded the not-portable versions, "Chatterino7.Installer.exe", and is all the same.

**Comment by hellishvictor** [comment]
I've downloaded the not-portable versions, "Chatterino.Installer.exe", and is all the same.

**Comment by hellishvictor** [comment]
I've downloaded the not-portable version, "Chatterino.Installer.exe", and is all the same.

**Comment by CJAnti** [comment]
I've had the same problem for about two weeks up to now. I didn't know, what triggered it though. Badges just didn't show up anymore.
Now I came here to search for tickets regarding this specific error.
I couldn't see any badges on the before mentioned link https://t.3v.fi/badges.html.
That reminded me, that I'm running a Pi-Hole on my network which subscribes to a bunch of adlists.
In the query log I could see that badges.twitch.tv was blocked by gravity, meaning by some of the adlists, and whitelisted it.
Now I can see the badges on the webpage and in Chatterino again.
I did some searching and found badges.twitch.tv on [EasyList](https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist).
EasyList is one of the most used lists out there and I don't really get, why someone would want to block the badges in a twitch chat (badges.instagram.com is in there, too).
Hope this helps!

**Comment by Felanbird** [comment]
Going to assume this was the same issue others have reported, which is the undocumented badge subdomain being blocked by various anti-trackers.

Resolved by #4537 which migrated badges to the Helix API - available on the https://github.com/Chatterino/chatterino2/releases/tag/nightly-build

**Comment by hellishvictor** [comment]
I tried that nightly-build but show me **"The procedure entry point Createdxgifactory2 could not be located in the dynamic link library dxgi.dll."**
![sshot-1](https://user-images.githubusercontent.com/34694956/232326221-75c7e132-ef91-47ad-bc96-ab93a8aa26d7.jpg)

**Comment by hellishvictor** [comment]
I tried that nightly-build but show me **"The procedure entry point Createdxgifactory2 could not be located in the dynamic link library dxgi.dll."**
![sshot-1](https://user-images.githubusercontent.com/34694956/232326221-75c7e132-ef91-47ad-bc96-ab93a8aa26d7.jpg)
and then it closes.

**Comment by Felanbird** [comment]
Which one of the assets did you download? Name is good enough

**Comment by hellishvictor** [comment]
That was with **"chatterino-windows-x86-64-Qt-6.5.0-EXPERIMENTAL.zip"**.
**"chatterino-windows-x86-64-Qt-5.15.2.zip"** does work but still doesn't show the badges:
![sshot-2](https://user-images.githubusercontent.com/34694956/232327389-28bd9c78-acf0-43fb-bbdd-de2c83c77f64.jpg)

**Comment by iProdigy** [comment]
You need to be logged in for the endpoint to work

**Comment by Felanbird** [comment]
Just so it's noted we do have a proper error when requesting badges while logged out.
![image](https://user-images.githubusercontent.com/41973452/232332866-1e5fff98-e3b6-4562-af51-4c06ea16b5f5.png)

Since you are unable to properly receive this error, along with the old badge API, and recent messages also do no load, this was very obviously an internet/operating system issue the whole time.

**Comment by hellishvictor** [comment]
> You need to be logged in for the endpoint to work

I have logged in and it doesn't work :(

**Comment by hellishvictor** [comment]
> Just so it's noted we do have a proper error when requesting badges while logged out. ![image](https://user-images.githubusercontent.com/41973452/232332866-1e5fff98-e3b6-4562-af51-4c06ea16b5f5.png)
> 
> Since you are unable to properly receive this error, along with the old badge API, and recent messages also do no load, this was very obviously an internet/operating system issue the whole time.

I have not issues with the internet at all. I though it was compatible with Win7,
Thank you anyway.

**Comment by Felanbird** [comment]
> I have not issues with the internet at all. I though it was compatible with Win7,

We've had some win7 users, and while they do have issues they've never reported any of the issues you have, which are loading responses from network requests, so 🤷

**Comment by hellishvictor** [comment]
> > I have not issues with the internet at all. I though it was compatible with Win7,
> 
> We've had some win7 users, and while they do have issues they've never reported any of the issues you have, which are loading responses from network requests, so shrug

![sshot-1](https://user-images.githubusercontent.com/34694956/232334821-7d56b7a0-12fd-4bdf-bf33-a6506c5d2da5.jpg)
Man, I tested right now [chatty](https://chatty.github.io/#download) and it goes perfect, it displays the badges and everything.

**Comment by iProdigy** [comment]
> Man, I tested right now [chatty](https://chatty.github.io/#download) and it goes perfect, it displays the badges and everything.

This is consistent with your network connection being slow. Chatty uses the exact same endpoint as us, but they have a *very* high [60 second read timeout](https://github.com/chatty/chatty/blob/6066caa01014f982ae7cf6aa5dadacdd277793e5/src/chatty/util/api/queue/Request.java#L54).

**Comment by hellishvictor** [comment]
I finally got it working using the [v7.4.5](https://github.com/SevenTV/chatterino7/releases/tag/v7.4.5) [portable with Qt5](https://github.com/SevenTV/chatterino7/releases/download/v7.4.5/Chatterino7.Portable.zip), since it's the last version that supports Win 7. Now I can see the badges.
